<<<<<<< HEAD
# Generated by Django 5.2 on 2025-06-07 01:04
=======
# Generated by Django 5.2 on 2025-05-08 18:34
>>>>>>> c5a73d0 (corrijindo migrations)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

<<<<<<< HEAD
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
=======
    dependencies = []
>>>>>>> c5a73d0 (corrijindo migrations)

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
<<<<<<< HEAD
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tag_uid', models.CharField(max_length=64, unique=True)),
                ('lote', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('tarja', models.CharField(choices=[('ST', 'Sem Tarja'), ('TA', 'Tarja Amarela'), ('TV', 'Tarja Vermelha'), ('TP', 'Tarja Preta')], default='ST', max_length=2)),
=======
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("tag_uid", models.CharField(max_length=64, unique=True)),
                ("lote", models.CharField(max_length=50)),
                ("validade", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tarja",
                    models.CharField(
                        choices=[
                            ("ST", "Sem Tarja"),
                            ("TA", "Tarja Amarela"),
                            ("TV", "Tarja Vermelha"),
                            ("TP", "Tarja Preta"),
                        ],
                        default="ST",
                        max_length=2,
                    ),
                ),
>>>>>>> c5a73d0 (corrijindo migrations)
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
<<<<<<< HEAD
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
=======
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("local", models.CharField(max_length=100)),
                ("origem_arduino", models.CharField(blank=True, max_length=100)),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.drug"
                    ),
                ),
>>>>>>> c5a73d0 (corrijindo migrations)
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.cart')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Saída'), ('ADJUSTMENT', 'Ajuste')], default='ENTRY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.drug')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.location')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-updated_at'],
                'unique_together': {('drug', 'location')},
            },
        ),
    ]
