# Generated by Django 5.2 on 2025-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='tarja',
            field=models.CharField(choices=[('ST', 'Sem Tarja')], default='ST', max_length=2),
        ),
    ]
