# Generated by Django 5.2 on 2025-06-19 20:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arduino', models.CharField(blank=True, max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
