# Generated by Django 5.2 on 2025-06-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_cart_updated_at_cart_updated_att'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='updated_att',
            new_name='updated_at',
        ),
    ]
