# Generated by Django 5.2 on 2025-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='local',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='location',
            name='origem_arduino',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
