# Generated by Django 5.2.1 on 2025-05-30 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_timestamp_location_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='RFIDReader',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_readers', to='inventory.location')),
            ],
            options={
                'verbose_name': 'RFID Reader',
                'verbose_name_plural': 'RFID Readers',
                'ordering': ['name'],
            },
        ),
    ]
